#!/usr/bin/env python3
"""
============================================================
  Phase 2 — Synthetic Training Data Generator

  Runs v7 strategy code backwards through 5 years of historical
  NSE data to produce ~10,000-30,000 labelled (signal, outcome)
  examples for the calibrated LR scoring model.

  WHY THIS EXISTS
  ───────────────
  The 239 backsim trades from production:
   1. Cover only one market regime (Mar-May 2026)
   2. Are biased toward signals that PASSED v6 filters
   3. Have N too small for stable LR feature weights

  This script regenerates the dataset by simulating v7 strategies
  on every (ticker, day) since 2020. For each day where any v7
  strategy fires, we:
    * Compute features using ONLY data ≤ that day (no look-ahead)
    * Simulate forward 15 days using OHLC (the label)
    * Record both gated-out and gated-in signals — the model needs
      to learn what to gate

  Result: thousands of labelled rows spanning multiple regimes
  (2020 COVID, 2021 rally, 2022 sideways, 2023 bull, 2024-25 mixed).

  USAGE
  ─────
    # Full run, ~30-60 min on GitHub Actions:
    python agent/build_training_data.py

    # Quick local validation, 5 tickers, 6 months:
    python agent/build_training_data.py --tickers RELIANCE,TCS,HDFCBANK,INFY,SBIN \\
                                         --start 2025-01-01 --end 2025-06-30 \\
                                         --csv /tmp/sample.csv

  OUTPUT
  ──────
  Writes rows to Supabase table `synthetic_training_data`. Schema in
  supabase_migration_v8.sql. Each row is one (ticker, signal_date)
  candidate with all v7 features + the forward-simulated outcome.

  LOOK-AHEAD BIAS GUARANTEE
  ─────────────────────────
  Every feature uses df.iloc[:i+1] only — never reaches forward.
  Every label uses df.iloc[i+1:i+1+H] only — strictly future.
  ATR, EMA, RSI, regime, dynamic_trade_levels are all
  point-in-time as long as df is sliced before the call.
============================================================
"""

from __future__ import annotations

import argparse
import os
import sys
import time
import math
import json
import warnings
from datetime import datetime, date, timedelta
from typing import Optional

import numpy as np
import pandas as pd
import yfinance as yf

warnings.filterwarnings("ignore")

# Reuse the v7 indicator and strategy code so the training data is
# generated by the *same* logic that runs in production.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from analyze import (
    ema, rsi, macd, bollinger, atr,
    sig_donchian, sig_ema, sig_rsi_trend_shift, sig_bb,
    dynamic_trade_levels,
    DEFAULT_PARAMS,
    NIFTY50,
)


# ─────────────────────────────────────────────
#  CONFIG
# ─────────────────────────────────────────────
HOLDING_PERIOD_DAYS = 15      # forward simulation window (matches backsimulate.py)
WARMUP_DAYS         = 100     # need at least this many bars before first signal
BATCH_INSERT_SIZE   = 500     # rows per Supabase upsert
DEFAULT_START       = "2020-04-01"   # post-COVID baseline; 5+ years of data
DEFAULT_END         = "2026-04-30"

# Universe for the first run. Use NIFTY50 from the agent (200 tickers).
# Many recent listings (SWIGGY, ETERNAL, WAAREEENER, etc.) will fail to
# fetch 5y of data — that's expected and skipped silently.
DEFAULT_UNIVERSE = NIFTY50


# ─────────────────────────────────────────────
#  REGIME (point-in-time)
# ─────────────────────────────────────────────
def compute_regime_series(nifty_df: pd.DataFrame) -> pd.Series:
    """
    Compute the v7 regime label for every day in the Nifty series.
    Uses 50-day and 200-day SMA cross — the same logic the live agent
    uses, but applied across the full history rather than just today.
    Returns a Series indexed by date with values BULLISH / NEUTRAL / BEARISH.
    """
    if len(nifty_df) < 200:
        return pd.Series(dtype=object)
    sma50  = nifty_df.Close.rolling(50,  min_periods=50).mean()
    sma200 = nifty_df.Close.rolling(200, min_periods=200).mean()
    out = pd.Series("NEUTRAL", index=nifty_df.index, dtype=object)
    out[(nifty_df.Close > sma50) & (sma50 > sma200)] = "BULLISH"
    out[(nifty_df.Close < sma50) & (sma50 < sma200)] = "BEARISH"
    return out


REGIME_SCORE = {"BULLISH": 1.0, "NEUTRAL": 0.5, "BEARISH": 0.0}


# ─────────────────────────────────────────────
#  FEATURE ENGINEERING (point-in-time)
# ─────────────────────────────────────────────
def compute_features(
    df_pit: pd.DataFrame,            # df sliced through day i (inclusive)
    nifty_pit: pd.DataFrame | None,  # nifty sliced through day i
    regime_label: str,
    today_sigs: dict,                # {strategy_name: -1/0/1}
    p: dict,                         # v7 params
) -> dict:
    """
    Build the feature vector for day i. Every value here must be
    derivable from data with index <= i.
    """
    if len(df_pit) < 30:
        return {}
    c     = df_pit.Close
    price = float(c.iloc[-1])
    if not math.isfinite(price) or price <= 0:
        return {}

    # ── Indicators
    rsi_v       = float(rsi(c, p["RSI_PERIOD"]).iloc[-1])
    _, _, h_v   = macd(c, p["MACD_FAST"], p["MACD_SLOW"], p["MACD_SIGNAL"])
    macd_h      = float(h_v.iloc[-1]) if pd.notna(h_v.iloc[-1]) else 0.0
    e_s         = float(ema(c, p["EMA_SHORT"]).iloc[-1])
    e_l         = float(ema(c, p["EMA_LONG"]).iloc[-1])
    ema_bull    = bool(e_s > e_l)
    atr_v       = float(atr(df_pit.High, df_pit.Low, c, p["ATR_PERIOD"]).iloc[-1])
    atr_pct     = round((atr_v / price) * 100, 3) if math.isfinite(atr_v) else None

    # ── Returns (price-only momentum)
    def _pct_change(n):
        if len(c) < n + 1: return None
        prev = float(c.iloc[-(n+1)])
        if prev <= 0: return None
        return round((price - prev) / prev * 100, 3)
    change_1d  = _pct_change(1)
    change_5d  = _pct_change(5)
    change_30d = _pct_change(30)

    # ── 52-week range
    lookback = min(252, len(c))
    high_52w = float(c.iloc[-lookback:].max())
    low_52w  = float(c.iloc[-lookback:].min())
    pct_from_52w_high = round((price - high_52w) / high_52w * 100, 2) if high_52w > 0 else None
    pct_from_52w_low  = round((price - low_52w)  / low_52w  * 100, 2) if low_52w  > 0 else None

    # ── Volume
    vol_20  = df_pit.Volume.rolling(20).mean().iloc[-1]
    vol_now = df_pit.Volume.iloc[-1]
    vol_ratio = round(float(vol_now) / float(vol_20), 3) if vol_20 and vol_20 > 0 else None

    # ── Strategy presence (binaries, plus n_firing for gate evaluation)
    has_donchian   = int(today_sigs.get("Donchian",        0) ==  1)
    has_ema        = int(today_sigs.get("EMA Crossover",   0) ==  1)
    has_rsi_trend  = int(today_sigs.get("RSI Trend Shift", 0) ==  1)
    has_bollinger  = int(today_sigs.get("Bollinger",       0) ==  1)
    n_firing       = has_donchian + has_ema + has_rsi_trend + has_bollinger
    single_strat   = int(n_firing == 1)
    multi_strat    = int(n_firing >= 2)

    # ── Trade levels (uses the same logic the live agent uses)
    levels = dynamic_trade_levels(df_pit, len(df_pit) - 1, price, p)
    risk_pct   = levels.get("risk_pct")
    reward_pct = levels.get("reward_pct")
    rr_ratio   = levels.get("rr_ratio")

    # ── Momentum vs Nifty (relative strength)
    mom_vs_nifty_30d = None
    if nifty_pit is not None and len(nifty_pit) >= 31 and change_30d is not None:
        n_close = float(nifty_pit.Close.iloc[-1])
        n_prev  = float(nifty_pit.Close.iloc[-31])
        if n_prev > 0:
            n_ret_30d = (n_close - n_prev) / n_prev * 100
            mom_vs_nifty_30d = round(change_30d - n_ret_30d, 3)

    return dict(
        price             = round(price, 2),
        rsi               = round(rsi_v, 2)  if math.isfinite(rsi_v) else None,
        macd_hist         = round(macd_h, 4),
        ema_bullish       = ema_bull,
        atr_pct           = atr_pct,
        change_1d         = change_1d,
        change_5d         = change_5d,
        change_30d        = change_30d,
        pct_from_52w_high = pct_from_52w_high,
        pct_from_52w_low  = pct_from_52w_low,
        vol_ratio         = vol_ratio,
        has_donchian      = has_donchian,
        has_ema           = has_ema,
        has_rsi_trend     = has_rsi_trend,
        has_bollinger     = has_bollinger,
        n_firing          = n_firing,
        single_strat      = single_strat,
        multi_strat       = multi_strat,
        risk_pct          = risk_pct,
        reward_pct        = reward_pct,
        rr_ratio          = rr_ratio,
        regime            = regime_label,
        regime_score      = REGIME_SCORE.get(regime_label, 0.5),
        mom_vs_nifty_30d  = mom_vs_nifty_30d,
    )


# ─────────────────────────────────────────────
#  FORWARD SIMULATION (the label generator)
#  Mirrors agent/backsimulate.py logic but uses the
#  v7 SL/target levels computed at signal day.
# ─────────────────────────────────────────────
def simulate_forward(
    df: pd.DataFrame,
    signal_idx: int,
    entry_price: float,
    sl: float | None,
    target: float | None,
    holding_period: int = HOLDING_PERIOD_DAYS,
) -> dict | None:
    """
    Walk forward from signal_idx+1 through up to `holding_period` bars,
    using full OHLC on each day. First-hit wins (SL takes priority on
    same-day touches).

    Returns:
      {
        was_win: bool,
        actual_return_pct: float,
        exit_reason: 'sl_hit' | 'target_hit' | 'timeout',
        days_held: int,
        mfe: float,         # max favorable excursion %
        mae: float,         # max adverse excursion %
        exit_price: float,
      }
      or None if there isn't enough forward data.
    """
    if entry_price is None or entry_price <= 0:
        return None
    end_idx = min(signal_idx + holding_period, len(df) - 1)
    if end_idx <= signal_idx:
        return None

    mfe_pct = 0.0
    mae_pct = 0.0
    for j in range(signal_idx + 1, end_idx + 1):
        try:
            high  = float(df.High.iloc[j])
            low   = float(df.Low.iloc[j])
            close = float(df.Close.iloc[j])
            popen = float(df.Open.iloc[j])
        except Exception:
            continue
        if not all(math.isfinite(v) for v in (high, low, close, popen)):
            continue

        # MFE / MAE updates using intra-day extremes
        mfe_pct = max(mfe_pct, (high - entry_price) / entry_price * 100)
        mae_pct = min(mae_pct, (low  - entry_price) / entry_price * 100)

        # SL check first (worst case for a long position)
        if sl is not None and sl > 0 and low <= sl:
            # Gap-down: filled at open, not the static SL
            fill = popen if popen <= sl else sl
            return dict(
                was_win=False,
                actual_return_pct=round((fill - entry_price) / entry_price * 100, 3),
                exit_reason="sl_hit",
                days_held=j - signal_idx,
                mfe=round(mfe_pct, 3),
                mae=round(mae_pct, 3),
                exit_price=round(fill, 2),
            )
        # Target check
        if target is not None and target > 0 and high >= target:
            fill = popen if popen >= target else target
            return dict(
                was_win=True,
                actual_return_pct=round((fill - entry_price) / entry_price * 100, 3),
                exit_reason="target_hit",
                days_held=j - signal_idx,
                mfe=round(mfe_pct, 3),
                mae=round(mae_pct, 3),
                exit_price=round(fill, 2),
            )

    # Timeout — close out at last available close
    last_close = float(df.Close.iloc[end_idx])
    if not math.isfinite(last_close):
        return None
    ret = (last_close - entry_price) / entry_price * 100
    return dict(
        was_win=ret > 0,
        actual_return_pct=round(ret, 3),
        exit_reason="timeout",
        days_held=end_idx - signal_idx,
        mfe=round(mfe_pct, 3),
        mae=round(mae_pct, 3),
        exit_price=round(last_close, 2),
    )


# ─────────────────────────────────────────────
#  TICKER RUNNER
# ─────────────────────────────────────────────
def fetch_ohlc(ticker: str, start: str, end: str) -> pd.DataFrame | None:
    """Fetch full OHLC for a ticker. Returns None on any failure."""
    try:
        df = yf.download(
            ticker + ".NS",
            start=start, end=end,
            progress=False, auto_adjust=True, threads=False,
        )
        if df is None or df.empty:
            return None
        # Flatten multi-level columns yfinance sometimes returns
        df.columns = [c[0] if isinstance(c, tuple) else c for c in df.columns]
        df = df.dropna(subset=["Open", "High", "Low", "Close"])
        return df if len(df) >= WARMUP_DAYS + HOLDING_PERIOD_DAYS else None
    except Exception:
        return None


def fetch_nifty(start: str, end: str) -> pd.DataFrame | None:
    """Fetch Nifty 50 (^NSEI) for regime + relative strength."""
    try:
        df = yf.download(
            "^NSEI",
            start=start, end=end,
            progress=False, auto_adjust=True, threads=False,
        )
        if df is None or df.empty:
            return None
        df.columns = [c[0] if isinstance(c, tuple) else c for c in df.columns]
        return df.dropna(subset=["Close"])
    except Exception:
        return None


def process_ticker(
    ticker: str,
    df: pd.DataFrame,
    nifty_df: pd.DataFrame,
    regime_series: pd.Series,
    p: dict,
) -> list[dict]:
    """
    Run v7 strategies across every day in df. Where any strategy fires
    BUY, record the (features, outcome) row. Returns a list of dicts
    ready for Supabase insertion.
    """
    rows: list[dict] = []
    if len(df) < WARMUP_DAYS + HOLDING_PERIOD_DAYS + 1:
        return rows

    # Pre-compute strategy signal series ONCE on the full df. Each
    # strategy's value at day i depends only on data <= i (we verified
    # this when reading their definitions in analyze.py: rolling/diff
    # operations are all backward-looking).
    sig_series = {
        "Donchian":        sig_donchian(df, p),
        "EMA Crossover":   sig_ema(df, p),
        "RSI Trend Shift": sig_rsi_trend_shift(df, p),
        "Bollinger":       sig_bb(df, p),
    }

    last_safe_idx = len(df) - HOLDING_PERIOD_DAYS - 1
    for i in range(WARMUP_DAYS, last_safe_idx + 1):
        # Today's signals at day i
        today_sigs = {name: int(s.iloc[i]) for name, s in sig_series.items()}
        buy_count  = sum(1 for v in today_sigs.values() if v ==  1)
        if buy_count == 0:
            continue

        signal_date = df.index[i].date().isoformat()

        # Regime at day i (point-in-time)
        try:
            regime_label = regime_series.loc[df.index[i]] if df.index[i] in regime_series.index else None
        except Exception:
            regime_label = None
        if not isinstance(regime_label, str):
            # nearest-prior fallback
            prior = regime_series[regime_series.index <= df.index[i]]
            regime_label = prior.iloc[-1] if len(prior) else "NEUTRAL"

        # Slice data up to and including day i
        df_pit    = df.iloc[: i + 1]
        nifty_pit = nifty_df[nifty_df.index <= df.index[i]] if nifty_df is not None else None

        # Features
        feats = compute_features(df_pit, nifty_pit, regime_label, today_sigs, p)
        if not feats:
            continue

        entry_price = feats["price"]
        sl  = feats.get("risk_pct")
        tgt = feats.get("reward_pct")
        # Convert risk/reward percentages back to absolute prices
        sl_price  = entry_price * (1 - sl  / 100) if sl  else None
        tgt_price = entry_price * (1 + tgt / 100) if tgt else None

        # Forward simulation (the label)
        outcome = simulate_forward(df, i, entry_price, sl_price, tgt_price)
        if outcome is None:
            continue

        # Apply v7 hard gates AS A FLAG (not a filter) — model needs
        # to learn what to gate, so we keep them in the dataset.
        gated_out = bool(
            (today_sigs.get("Donchian",0)==1 or today_sigs.get("EMA Crossover",0)==1 or
             today_sigs.get("RSI Trend Shift",0)==1 or today_sigs.get("Bollinger",0)==1)
            and (feats["multi_strat"] == 1 or feats["regime"] == "BEARISH")
        )

        rows.append({
            "ticker":       ticker,
            "signal_date":  signal_date,
            "gated_out":    gated_out,
            **feats,
            **outcome,
        })

    return rows


# ─────────────────────────────────────────────
#  PERSISTENCE
# ─────────────────────────────────────────────
def get_supabase_client():
    """Lazy import + connect; returns None if env vars missing."""
    if not (os.environ.get("SUPABASE_URL") and os.environ.get("SUPABASE_KEY")):
        return None
    from supabase import create_client
    return create_client(os.environ["SUPABASE_URL"], os.environ["SUPABASE_KEY"])


def write_rows(rows: list[dict], sb=None, csv_path: str | None = None) -> None:
    """Persist rows to Supabase in batches, OR write a CSV for local validation."""
    if not rows:
        return
    if csv_path:
        df = pd.DataFrame(rows)
        write_header = not os.path.exists(csv_path)
        df.to_csv(csv_path, mode="a", index=False, header=write_header)
    if sb is not None:
        for k in range(0, len(rows), BATCH_INSERT_SIZE):
            batch = rows[k : k + BATCH_INSERT_SIZE]
            try:
                sb.table("synthetic_training_data").insert(batch).execute()
            except Exception as e:
                print(f"  ⚠️  Supabase insert failed for batch of {len(batch)}: {e}")


# ─────────────────────────────────────────────
#  MAIN
# ─────────────────────────────────────────────
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--tickers", default=None,
                    help="Comma-separated tickers (default: NIFTY50 list)")
    ap.add_argument("--start",   default=DEFAULT_START)
    ap.add_argument("--end",     default=DEFAULT_END)
    ap.add_argument("--csv",     default=None,
                    help="If set, also write rows to this CSV (for local validation)")
    ap.add_argument("--purge",   action="store_true",
                    help="Truncate synthetic_training_data before inserting")
    args = ap.parse_args()

    tickers = (args.tickers.split(",") if args.tickers else DEFAULT_UNIVERSE)
    print(f"\n📊 Phase 2 training data generator")
    print(f"   Tickers : {len(tickers)}")
    print(f"   Window  : {args.start}  →  {args.end}")
    print(f"   Forward : {HOLDING_PERIOD_DAYS} bars")
    print(f"   Output  : {'csv:' + args.csv if args.csv else ''} {'+supabase' if os.environ.get('SUPABASE_URL') else ''}\n")

    sb = get_supabase_client()
    if sb is not None and args.purge:
        try:
            sb.table("synthetic_training_data").delete().neq("ticker", "__never__").execute()
            print("   Purged synthetic_training_data\n")
        except Exception as e:
            print(f"   ⚠️  Purge failed: {e}\n")
    if args.csv and os.path.exists(args.csv):
        os.remove(args.csv)

    # ── Fetch Nifty once
    print("   Fetching Nifty 50 benchmark...")
    nifty_df = fetch_nifty(args.start, args.end)
    if nifty_df is None:
        print("   ❌ Nifty fetch failed; aborting.")
        return
    regime_series = compute_regime_series(nifty_df)
    print(f"   Nifty bars: {len(nifty_df)} | regime samples: {len(regime_series)}\n")

    P = DEFAULT_PARAMS
    grand_total = 0
    skipped     = 0
    t0 = time.time()
    for n, ticker in enumerate(tickers, 1):
        df = fetch_ohlc(ticker, args.start, args.end)
        if df is None:
            skipped += 1
            print(f"   {n:>3}/{len(tickers)}  {ticker:<14}  ⚠️  insufficient data")
            continue
        rows = process_ticker(ticker, df, nifty_df, regime_series, P)
        write_rows(rows, sb=sb, csv_path=args.csv)
        grand_total += len(rows)
        print(f"   {n:>3}/{len(tickers)}  {ticker:<14}  bars={len(df):4}  signals={len(rows):4}  "
              f"running total={grand_total:6}")
        # Light rate-limit: pause every 25 tickers
        if n % 25 == 0:
            time.sleep(2)

    dt = time.time() - t0
    print(f"\n   ✅ Done in {dt/60:.1f}m")
    print(f"      Tickers processed : {len(tickers) - skipped}")
    print(f"      Tickers skipped   : {skipped} (insufficient history)")
    print(f"      Training rows     : {grand_total}")


if __name__ == "__main__":
    main()
